name: Terraform Destroy (manual, no plan)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type EXACTLY: DESTROY'
        required: true
        type: string

env:
  AWS_REGION: ap-southeast-1

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra   # <- set to the folder with .tf files

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false
        # If you use an S3 backend file:
        # run: terraform init -input=false -backend-config=backend-prod.hcl

      - name: Terraform Destroy (no plan step)
        run: terraform destroy -auto-approve -input=false -no-color
